#!/usr/bin/env node
"use strict";
// AUTO-GENERATED by scripts/gen-clis.mjs — do not edit by hand.
const { run } = require("@stuffbucket/ai-cli-core");
const { version } = require("./package.json");
run({ cli: "codex", version }, process.argv.slice(2));
