#!/usr/bin/env node
// Generate the per-CLI npx wrapper packages from versions.json.
//
// Each wrapper is a thin package whose VERSION === the CLI version (1:1), so the
// npm package and the container image are always in sync:
//   npx @stuffbucket/claude-code@2.1.158  ->  ghcr.io/stuffbucket/claude-code:2.1.158
//
// This runs in CI (and locally via `npm run gen`); `npm run check:gen` fails if
// the committed wrappers drift from versions.json.

import { readFileSync, writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const versions = JSON.parse(readFileSync(join(root, "versions.json"), "utf8"));
const coreVersion = JSON.parse(
  readFileSync(join(root, "packages/core/package.json"), "utf8"),
).version;

// npm package short-name per image (convention: @stuffbucket/ai-cli-<short>).
// Defaults to the image key; override where the CLI command differs from the
// image name (the claude-code image's command is `claude`).
const SHORT = { "claude-code": "claude" };
const pkgShort = (cli) => SHORT[cli] || cli;
const pkgName = (cli) => `@stuffbucket/ai-cli-${pkgShort(cli)}`;

const runJs = (cli) => `#!/usr/bin/env node
"use strict";
// AUTO-GENERATED by scripts/gen-clis.mjs — do not edit by hand.
const { run } = require("@stuffbucket/ai-cli-core");
const { version } = require("./package.json");
run({ cli: ${JSON.stringify(cli)}, version }, process.argv.slice(2));
`;

const pkgJson = (cli, meta) => {
  // bin name must equal the package's unscoped name so `npx @stuffbucket/ai-cli-x`
  // resolves the bin without `-p`.
  const bin = `ai-cli-${pkgShort(cli)}`;
  return {
    name: pkgName(cli),
    version: meta.version,
    description: `npx wrapper that runs the ${cli} CLI via the ghcr.io/stuffbucket/${meta.image} container image (version-locked 1:1 with the CLI)`,
    license: "MIT",
    repository: {
      type: "git",
      url: "git+https://github.com/stuffbucket/ai-cli-images.git",
      directory: `packages/clis/${cli}`,
    },
    bin: { [bin]: "run.js" },
    dependencies: { "@stuffbucket/ai-cli-core": `^${coreVersion}` },
    files: ["run.js"],
    engines: { node: ">=20" },
  };
};

for (const [cli, meta] of Object.entries(versions)) {
  const dir = join(root, "packages/clis", cli);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify(pkgJson(cli, meta), null, 2) + "\n",
  );
  const run = join(dir, "run.js");
  writeFileSync(run, runJs(cli));
  chmodSync(run, 0o755);
  console.log(`generated ${pkgName(cli)}@${meta.version}`);
}
